### ISSUE TITLE
Solve an errata on locale.es.properties

### ISSUE THREAD

**Issue by Carlos-SS-PMI** [moltenform/scite-files#51]
Hi!
To solve an errata on "locale.es.properties" file related to "Toggle Bookmark" translation, please, push attached file.
[locale.es.properties.zip](https://github.com/moltenform/scite-files/files/6624158/locale.es.properties.zip)
Thanks!

**Comment by BenF-lively** [comment]
I will add this soon, thank you!

**Comment by moltenform** [comment]
Done. Thank you for contributing to the project!
