### ISSUE TITLE
SciTE Windows installer link is broken

### ISSUE THREAD

**Issue by igelover** [moltenform/scite-files#59]
SciTE Windows installer link is broken, any chance you can provide an alternative?

**Comment by BenF-lively** [comment]
Hi,

The Windows installer was provided by a 3rd party, it's too bad that the link no longer works though. Perhaps the 'Single file' links above it will help, those don't need to be installed and can just be double-clicked to open.

If that doesn't fill your needs, I would recommend contacting the scite mailing list here, https://groups.google.com/g/scite-interest?pli=1 , and there might be more information there.

**Comment by igelover** [comment]
Link working again, thanks!
