### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hugok79** [moltenform/scite-files#67]
@moltenform @georgeraraujo 

No big deal, but there is a typo in the word `specifiy`, it has an extra `i`. It should be`specify`
The original/source file is fine so it's only in the **pt_BR** file.

https://github.com/moltenform/scite-files/blob/bec75171c44ffa561aa590b149ff196f6aacb898/files/files/translations/locale.pt_BR.properties#L13

**Comment by moltenform** [comment]
Resolved in all 30 affected files,

Thanks for pointing it out!

https://github.com/moltenform/scite-files/commit/b0f75959fe0e0cadb96d31a807f6db5104655c62
