### ISSUE TITLE
我的中文翻译

### ISSUE THREAD

**Issue by Amanxisf** [moltenform/scite-files#69]
`translation.encoding=UTF-8
# 简体中文 Scite v5.3.2
# 默认位置 $(SciteDefaultHome)/locale.properties
[★菜单]
File=文件(&F)
 @New=新建文件(&N)
Open=打开(&O)
Open Selected Filename=打开选取地址(&F)
Revert=重读文件(&R)
Close=关闭文件(&W)
Save=保存文件(&S)
Save As=文件另存为(&A)
Save a Copy=文件备份(&Y)
Copy Path=复制文件路径(&H)
Encoding=文件编码(&G)
Code Page Property=ASCII (&A)
UTF-16 Big Endian=UTF-16 BE (&Z)
UTF-16 Little Endian=UTF-16 LE (&X)
UTF-8 with BOM=UTF-8 BOM(&S)
UTF-8=UTF-8(&D)
Export=导出(&E)
As HTML=HTML
As RTF=RTF
As TeX=TeX
As PDF=PDF
As LaTeX=LaTeX
As XML=XML
Page Setup=打印安装(&U)
Print=打印(&P)
Load Session=载入会话(&L)
Save Session=保存会话(&V)
Reboot=重启(&Z)
Exit=退出(&X)
[右键菜单]
Edit=编辑 &E
Undo=撤销 &U
Redo=重做 &R
Cut=剪切 &T
Copy=复制 &C
Paste=粘贴 &B
Duplicate=复写 &E
Delete=删除 &D
Select All=全选 &A
[编辑菜单]
Copy as RTF=复制为 RT&F
Match Brace=匹配括号(&E)
Select to Brace=选至括号(&O)
Show Calltip=参数补全(&H)
Complete Symbol=函数补全(&Y)
Complete Word=自动补全(&W)
Expand Abbreviation=展开缩写(&B)
Stream Comment=流注释(&N)
Box Comment=块注释(&X)
Block Comment or Uncomment=行注释(&M)
Insert Abbreviation=插入缩写(&I)
Make Selection Uppercase=转为大写(&S)
Make Selection Lowercase=转为小写(&L)
Paragraph=段落(&G)
Join=合并(&J)
Split=分割(&S)
Reverse Selected Lines=反选选择行
[搜索菜单]
Search=搜索(&S)
Find=查找(&F)
Find Next=查找下一个(&G)
Find Previous=查找上一个(&V)
Find in Files=在文件中查找(&I)
Replace=替换(&D)
Filter=筛选器
Incremental Search=增量查找(&A)
Next Bookmark=下一书签(&E)
Previous Bookmark=上一书签(&R)
Toggle Bookmark=书签切换(&T)
Clear all Bookmarks=清除书签(&W)
Selection Add Next=增选下一个(&N)
Selection Add Each=增选每一个(&C)
Select All Bookmarks=选择所有书签
[查看菜单]
View=查看(&V)
Toggle current fold=折叠/展开(&C)
Toggle all folds=折叠/展开所有(&A)
Full Screen=全屏(&N)
Tool Bar=工具栏(&T)
Tab Bar=标签栏(&B)
Status Bar=状态栏(&S)
Whitespace=空白标示(&W)
End of Line=结束符(&E)
Indentation Guides=缩进标示(&I)
Line Numbers=行号(&L)
Margin=页边(&M)
Fold Margin=折叠页边(&F)
Output=控制台(&D)
Parameters=运行参数(&P)
Hide=隐藏控制台
[工具菜单]
Tools=工具(&X)
Compile=编译(&C)
Build=构建(&B)
AStyle=格式化(&F)
Go=执行(&G)
Clean=清理(&L)
Stop Executing=中止执行
Next Message=下一条消息
Previous Message=上一条消息
Clear Output=清空控制台
Switch Pane=切换控面板

Execute Selection=执行选择文本
[选项菜单]
Options=选项(&O)
Open Files Here=当前目录(&H)
Always On Top=总是置顶(&Q)
Wrap=自动换行(&W)
Wrap Output=自动换行(控制台)(&P)
Read-Only=只读(&R)
Vertical Split=垂直控制台(&V)
Line End Characters=结束符(&L)
CR + LF=CR &+ LF (Windows)
CR=&CR (MacOS)
LF=&LF (UNIX/Linux)
Convert Line End Characters=转换结束符(&C)
Change Indentation Settings=更改缩进设置(&T)
Use Monospaced Font=使用等宽字体(&M)
Open Local Options File=○本地配置 Scite.properties
Open Directory Options File=○目录配置 SciTEDirectory.properties
Open User Options File=○用户配置 SciteUser.properties
Open Global Options File=★ 全局选项(&G)
Open Abbreviations File=缩写变量(&A)
Open Lua Startup Script=启动脚本(&I)
[标签菜单]
Buffers=标签(&B)
Previous=上一个(&P)
Next=下一个(&N)
Close All=全部关闭(&C)
Save All=全部保存(&S)
[语言菜单]
Language=语言(&L)
Lexer=解析器
NewAction=新操作
[帮助菜单]
Help=帮助(&H)
SciTE Help=SciTE帮助(&M)
Sc1 Help=SciTE帮助(&M)
About Sc1=关于(&A)
About SciTE=关于(&A)
Version=版本
by=by
[右键菜单]
Prev File=上一文件(&P)
Next File=下一文件(&N)
Clean Console=清除控制台(&C)
Clean BookMark=清除书签(&V)
Drop Selection=丢弃选择(&S)
[★对话框]
# 通用
OK=确定
Cancel=取消
Yes=是
No=否
# 关于对话框
TranslationCredit=翻译组:\n\
	Amanout\n\
	Chii Liao\n\
	Daniel Lin\n\
	Edward Hsieh\n\
	Gong Weizheng\n\
	Linnchord\n\
	Calon Xu\n\
	emlvvh\n\
	Lenny(aries215)
Contributors:=贡献者:
# 文件对话框
# Open File=打开文件
Save File=保存文件
Save File As=另存文件为
Export File As HTML=导出为 HTML 文件
Export File As RTF=导出为 RTF 文件
Export File As LaTeX=导出为 LaTeX 文件
Export File As TeX=导出为 Tex 文件
Export File As PDF=导出为 PDF 文件
Export File As XML=导出为 XML 文件
Save Current Session=保存当前会话
Custom Filter=自定过滤
# 缩进对话框
Indentation Settings=缩进设置
Tab Size:=制表宽度(&T):
Indent Size:=缩进宽度(&I):
Use tabs:=使用制表符(&B):
Use tabs=使用制表符
Convert=转换(&C)
# 参数对话框
Execute=执行
Set=设置(&S)
8 Bit=8位
# 缩写对话框
Abbreviation:=缩写(&A):  ALT+↓
Insert=插入(&I)
# 宏对话框
List Macros=列出所有宏
Run Current Macro=运行当前宏
Record Macro=录制宏
Stop Recording Macro=停止录制宏

# 跳转对话框
Go To=定位(&G)
Destination Line Number:=目标行:
Current line:=当前行:
Last line:=最末行:
Destination Line:=目标行(&D):
Column:=列(&C):

Untitled=未命名
Search for:=搜索:
# 过滤
All Source=源代码
All Files (*.*)=所有文件(*.*)
All Files (*)=所有文件(*.*)
Show hidden files=显示隐藏文件
Hidden Files (.*)=隐藏文件(.*)
# 状态栏
READ=只读
INS=插入
OVR=覆盖
[搜索对话框]
# 增量搜索
Find:=查找(&F):
Replace:=替换(&V):
Replace all=替换全部(&A)
Replace in Selection=在选取范围内替换(&D)
Mark all=标记所有(&A)
In Selection=替换选取范围(&S)
# 搜索选项
Match whole word only=全字匹配(ALT+W)(&W)
Case sensitive=区别大小写(ALT+C)(&C)
Regular expression=正则表达式(ALT+E)(&E)
Wrap around=循环查找(ALT+R)(&R)
Transform backslash expressions=转换反斜线符号(ALT+B)(&B)
Filter:=筛选器
Context=显示包含内容的行
# 多文件搜索
..=&P
Find what:=查找(&A):
Files:=文件(&S):
Directory:=目录(&D):
Browse=浏览(&B)
Select a folder to search from=选择要搜索的文件夹
# 其他
Match case=匹配大小写(&C)
Replacements:=替换计数:
Replace in Buffers=所有标签中替换(&U)
Removed 1 line(s).=已删除了 '^0' 行。
Replace with:=替换为(&P):
Direction=查找方向
Reverse direction=反向查找
Up=向上(ALT+U)(&U)
Down=向下(ALT+D)(&D)

`

**Comment by moltenform** [comment]
Hi,

Thank you for contributing!
Do you think you could start with the file here,
https://raw.githubusercontent.com/moltenform/scite-files/master/files/files/translations/locale.zh_s.properties
make your additions onto that file, and then send again?

-Ben

**Comment by moltenform** [comment]
Done,

Now if you go to https://raw.githubusercontent.com/moltenform/scite-files/master/files/files/translations/locale.zh_s.properties , your updates will be there. Does it look good?

-Ben

**Comment by Amanxisf** [comment]
> Done,
> 
> Now if you go to https://raw.githubusercontent.com/moltenform/scite-files/master/files/files/translations/locale.zh_s.properties , your updates will be there. Does it look good?
> 
> -Ben

It`s good. Your project has own

I has improved properties lexer style and highlighting,and include fold.
It`s look better and easyer to edit in SciTE:
![props](https://github.com/moltenform/scite-files/assets/155814513/b78e5373-4b55-482c-b493-2bc3a82c9ebb)
